language: python
os: [
  "linux"
  ]
dist: "xenial"
python:
- '3.8'
- 'pypy3'
# command to install dependencies
install:
  - pip install -U tox-travis
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - tox
