language: python
os: [
  "linux"
  ]
dist: "xenial"
python:
- '3.8'
- 'pypy3'
# command to install dependencies
install:
  - pip install -U tox-travis
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - tox
# deploy new versions to PyPI
# deploy:
#   provider: pypi
#   distributions: sdist bdist_wheel
#   user: audreyr
#   password:
#     secure: PLEASE_REPLACE_ME
#   on:
#     tags: true
#     repo: audreyr/python_boilerplate
#     python: 3.8
